clear; clc;
close all;
addpath('functions/'); 
set(0,'defaultAxesFontSize',16);
%% COMPUTE GG OBSERVATION RESIDUALS DUE TO ATTITUDE ERRORS
% Description: using GG observations generated by OMSODP and attitude
% errors according to Encarnacao et.al. 2025, compute the effect of NSM in
% removing atittude errors for the different eigenvalues.
% Author: Sergio Coll Ibars
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%%                Mesurement mask 
%           xx xy xz yx yy yz zx zy zz
mask     =  [1, 1, 1, 0, 1, 1, 0, 0, 1]';

%%             Read or compute attitude errors
read = 1;

%% Extract GG observations
folderPath = "/Users/sergiocollibars/Documents/GG_observations/120by120";
[GG_obs]   = parser_GG_obs_MSODP(folderPath);

%% plot GG
t0         = datetime(2000,1,1,12,0,0,'TimeZone','UTC');
t_dateTime = t0 + seconds(GG_obs(:, 1));
t          = GG_obs(:, 1); Nt = length(t);

yylbl = ['XX', 'XY', 'XZ', 'YY', 'YZ', 'ZZ'];
figure();
for k = 1:6
    subplot(2, 3, k);
    plot(t_dateTime, GG_obs(:, k+1)./1E-9, 'LineWidth', 2, 'Color', 'b'); 
    title(yylbl(k)); ylabel('[Eotvos]')
    grid on;
end
sgtitle('GG Observations from ' + string(t_dateTime(1)) + ' to ' + ...
    string(t_dateTime(end)));

%% Compute state errors
fs = 1 / (t(2) -t(1)); % Hz
if(read == 0)
    disp('  Generating state errors ... ')
    
    plotCommand = 0;
    [At1] = create_noise_from_PSD(fs, Nt/fs, plotCommand); % yaw error
    [At2] = create_noise_from_PSD(fs, Nt/fs, plotCommand); % pitch error
    [At3] = create_noise_from_PSD(fs, Nt/fs, plotCommand); % roll error
    
    att_Err = [At1,At2,At3]';
else
    disp('  Reading state errors ...')
    path = '/Users/sergiocollibars/Documents/att_residuals/';
    file = 'attitude_residuals_xx400.txt';
    data = readmatrix(strcat(path,file));
    
    At1 = data(:, 1); % yaw error
    At2 = data(:, 2); % pitch error
    At3 = data(:, 3); % roll error
    
    att_Err = [At1,At2,At3]';
end

figure(); tt = ["yaw error", "pitch error", "roll error"];
for j = 1:3
    subplot(1, 3, j)
    plot(t_dateTime, att_Err(j, :), 'LineWidth', 2); grid on;
    title(tt(j)); ylabel('[rad]');
end

figure()
scale = 3600 * 180 / pi;
semilogy(t_dateTime, vecnorm(att_Err) * scale, '.', 'LineStyle', 'none'); grid on;
title("Attitude error magnitude"); ylabel('[arcseconds]');

%% Add angular errors
[GG_rot, GG_nom] = rotate_GG_obs(GG_obs,att_Err);
prefit           = GG_rot(:, 2:end) - GG_nom(:, 2:end);

dY               = prefit(:, logical(mask))'; % mask x Nt
signal           = GG_nom(:, 2:end);
signal_mask      = signal(:, logical(mask))';

%% Instrument noise
GG_sigma         = 2^(-1/2) * 1E-14;   % [s^-2 / sqrt(Hz)]

%% Apply NSM to eliminate 1st order orientation errors
disp('  Computing NSM')
dY_NSM     = nan(1, Nt, sum(mask)); signal_NSM = dY_NSM; 
for j = 1:Nt 
    [Hrot_grad] = compute_rotPartials_analy(GG_nom(j, 2:end)', eye(3));
    [S, V, D]   = svd(Hrot_grad(logical(mask), :)');
    for i = 1:sum(mask)
        V_rot               = D(:, i);
        P_rot               = V_rot * V_rot';
    
        dY_NSM(1, j, i)     = V_rot' * dY(:, j);
        signal_NSM(1, j, i) = V_rot' * signal_mask(:, j);
    end
end

%% Power Spectral Density of measurement residuals
figure(); hold on;

colors = lines(sum(mask));
h      = gobjects(sum(mask),1);   % store handles for legend

for k = 1:sum(mask)
    signal1    = squeeze(dY_NSM(:, :, k)) ./ 1E-9;
    [Pxx1, f1] = compute_PSD(signal1, fs);
    signal2    = squeeze(signal_NSM(:, :, k)) ./ 1E-9;
    [Pxx2, f2] = compute_PSD(signal2, fs);

    c = colors(k,:);

    h(k) = loglog(f2, sqrt(Pxx2), 'Color', c, 'LineWidth', 1.5); % legend handle
    loglog(f1, sqrt(Pxx1), '--', 'Color', c, 'LineWidth', 1.5);
end

legend(h, arrayfun(@(k) sprintf('\\lambda_{%d}', k),...
    1:sum(mask), 'UniformOutput', false));
set(gca, 'XScale', 'log', 'YScale', 'log');   % force log axes
grid on; ylabel('Eotvos'); xlabel('Hz');
title('NSM signal for different modes');


%% AUXILIARY FUNCTIONS
function [Pxx, f] = compute_PSD(X, Fs, window, noverlap, nfft)
% plotPSD_multiChannel  Plot PSD for each channel (row) of X in one figure.
%
% INPUTS
%   X        : N x Nt data matrix (N channels, Nt time samples)
%   Fs       : sampling frequency [Hz]
%   window   : (optional) pwelch window (scalar length or vector). Default: Hann(1024)
%   noverlap : (optional) number of overlapping samples. Default: 50% of window length
%   nfft     : (optional) FFT length. Default: max(256, 2^nextpow2(window length))
%
% NOTES
%   - Uses Welch PSD estimate (pwelch)
%   - Plots all channels on a single axes (log-log)
%   - Assumes each row is a time series

    narginchk(2,5);

    if isempty(X) || ~ismatrix(X)
        error('X must be a non-empty 2D matrix of size N x Nt.');
    end
    if ~isscalar(Fs) || Fs <= 0
        error('Fs must be a positive scalar (Hz).');
    end

    [N, Nt] = size(X);

    % Defaults
    if nargin < 5 || isempty(window)
        winLen = min(1024, Nt);
        window = hann(winLen, 'periodic');
    else
        if isscalar(window)
            winLen = min(window, Nt);
            window = hann(winLen, 'periodic');
        else
            winLen = min(length(window), Nt);
            window = window(:);
            if length(window) ~= winLen
                window = window(1:winLen);
            end
        end
    end

    if nargin < 6 || isempty(noverlap)
        noverlap = floor(0.5 * winLen);
    else
        noverlap = min(noverlap, winLen-1);
    end

    if nargin < 7 || isempty(nfft)
        nfft = max(256, 2^nextpow2(winLen));
    end

    % Compute PSDs
    for i = 1:N
        xi = X(i,:);
        if all(~isfinite(xi))
            warning('Channel %d contains no finite values; skipping.', i);
            continue;
        end

        % Remove mean (helps with DC dominating)
        xi = xi - mean(xi, 'omitnan');

        % Replace NaNs/Infs (pwelch can't handle NaNs)
        bad = ~isfinite(xi);
        if any(bad)
            % simple linear interpolation over bad samples
            t = 1:Nt;
            good = ~bad;
            if nnz(good) < 2
                warning('Channel %d has too few valid samples; skipping.', i);
                continue;
            end
            xi(bad) = interp1(t(good), xi(good), t(bad), 'linear', 'extrap');
        end

        [Pxx, f] = pwelch(xi, window, noverlap, nfft, Fs, 'onesided');
    end
end