clear; clc;
close all;
addpath('functions/'); 
set(0,'defaultAxesFontSize',16);
%% COMPUTE GG OBSERVATION RESIDUALS DUE TO ROTATION ERRORS
% Description: using GG observations generated by OMSODP and attitude
% errors according to Encarnacao et.al. 2025, compute the effect of NSM in
% removing atittude errors for the different eigenvalues.
% Author: Sergio Coll Ibars
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%%                Mesurement mask 
%           xx xy xz yx yy yz zx zy zz
mask     =  [1, 0, 1, 0, 1, 0, 0, 0, 1]';

%% Extract GG observations
folderPath = "/Users/sergiocollibars/Documents/GG_observations/120by120/500km";
[GG_obs]   = parser_GG_obs_MSODP(folderPath);

%% plot GG
t0         = datetime(2000,1,1,12,0,0,'TimeZone','UTC');
t_dateTime = t0 + seconds(GG_obs(:, 1));
t          = GG_obs(:, 1); Nt = length(t);

yylbl = ["XX", "XY", "XZ", "YY", "YZ", "ZZ"];
figure();
for k = 1:6
    subplot(2, 3, k);
    plot(t_dateTime, GG_obs(:, k+1)./1E-9, 'LineWidth', 2, 'Color', 'b'); 
    title(yylbl(k)); ylabel('[Eotvos]')
    grid on;
end
sgtitle('GG Observations from ' + string(t_dateTime(1)) + ' to ' + ...
    string(t_dateTime(end)));

%% Compute state errors
fs = 1 / (t(2) -t(1)); % Hz

% angular Velocity error
load("nominal_angVel_500km.mat");
sigmaAngVel = 2E-8; % [rad/s];
deltaAngVel = normrnd(0, sigmaAngVel,    [3, Nt]);

% compute Angular acceleration
I = [152,-23.4,5.5;-23.4,2690.8,0.9;-5.5,0.9,2652.6];
[M]          = compute_ExternalTorque(angVel(:, 1:Nt), I, 5);
[angAcc_nom] = compute_angAcc(angVel(:, 1:Nt),I, M);
[angAcc]     = compute_angAcc(angVel(:, 1:Nt)+deltaAngVel,I, M);

%% Add angular errors
[GG_rot, GG_nom]            = rotate_GG_obs(GG_obs,zeros(3, Nt));
[~,~,~,dyad2_angVel_nom]    = compute_dyad(angVel(:, 1:Nt));
[~,~,~,dyad2_angVel]        = compute_dyad(angVel(:, 1:Nt)+deltaAngVel);
[~,~,dyad_angAcc_nom,~]     = compute_dyad(angAcc_nom(:, 1:Nt));
[~,~,dyad_angAcc,~]         = compute_dyad(angAcc(:, 1:Nt));

prefit           = GG_rot(:, 2:end) - GG_nom(:, 2:end) ...
                   + dyad2_angVel'  - dyad2_angVel_nom' ...
                   + dyad_angAcc'   - dyad_angAcc_nom';

dY               = prefit(:, logical(mask))'; % mask x Nt
signal           = GG_nom(:, 2:end);
signal_mask      = signal(:, logical(mask))';

%% Apply NSM to eliminate 1st order orientation errors
disp('  Computing NSM')
dY_NSM     = nan(1, Nt, sum(mask)); signal_NSM = dY_NSM; 
for j = 1:Nt 
    [H_w]           = angularVel_dyad2_partials(angVel(:, j));
    [H_wdot]        = angularAcc_dyad_partials(5, angVel(:, j), I);
    H               = H_w+H_wdot;
    [S1, V1, D1]   = svd(H(logical(mask), :)');

    D = D1;
    for i = 1:sum(mask)
        V_rot               = D(:, i);
        P_rot               = V_rot * V_rot';
    
        dY_NSM(1, j, i)     = V_rot' * dY(:, j);
        signal_NSM(1, j, i) = V_rot' * signal_mask(:, j);
    end
end

%% Plot NSM residuals time series
sigma_noise = sqrt(1E-10 * fs); % [Eotvos] 
noise       = normrnd(0, sigma_noise, [1, Nt]);
plot_residuals(t_dateTime, dY_NSM, noise, sigma_noise);

%% Power Spectral Density of NSM measurement residuals
figure(); hold on;

colors = lines(sum(mask));
h      = gobjects(sum(mask),1);   % store handles for legend

for k = 1:sum(mask)
    signal1    = squeeze(dY_NSM(:, :, k)) ./ 1E-9;
    [Pxx1, f1] = compute_PSD(signal1, fs);
    signal2    = squeeze(signal_NSM(:, :, k)) ./ 1E-9;
    [Pxx2, f2] = compute_PSD(signal2, fs);

    c = colors(k,:);

    h(k) = loglog(f2, sqrt(Pxx2), 'Color', c, 'LineWidth', 1.5); % legend handle
    loglog(f1, sqrt(Pxx1), '--', 'Color', c, 'LineWidth', 1.5);
end

legend(h, arrayfun(@(k) sprintf('\\lambda_{%d}', k),...
    1:sum(mask), 'UniformOutput', false));
set(gca, 'XScale', 'log', 'YScale', 'log');   % force log axes
grid on; ylabel('Eotvos'); xlabel('Hz');
title('NSM signal for different modes');

%% Power Spectral Density of original measurement residuals
figure(); hold on;
tensor_signal = GG_nom(:, 2:end)';
tt            = tensor_signal(logical(mask), :);
for k = 1:sum(mask)
    signal1    = squeeze(dY(k, :)) ./ 1E-9;
    [Pxx1, f1] = compute_PSD(signal1, fs);
    signal2    = squeeze(tt(k, :)) ./ 1E-9;
    [Pxx2, f2] = compute_PSD(signal2, fs);

    c = colors(k,:);

    h(k) = loglog(f2, sqrt(Pxx2), 'Color', c, 'LineWidth', 1.5); % legend handle
    loglog(f1, sqrt(Pxx1), '--', 'Color', c, 'LineWidth', 1.5);
end
set(gca, 'XScale', 'log', 'YScale', 'log');   % force log axes
grid on; ylabel('Eotvos'); xlabel('Hz');
title('Original signal for different components');

%% AUXILIARY FUNCTIONS
function [Pxx, f] = compute_PSD(X, Fs, window, noverlap, nfft)
% plotPSD_multiChannel  Plot PSD for each channel (row) of X in one figure.
%
% INPUTS
%   X        : N x Nt data matrix (N channels, Nt time samples)
%   Fs       : sampling frequency [Hz]
%   window   : (optional) pwelch window (scalar length or vector). Default: Hann(1024)
%   noverlap : (optional) number of overlapping samples. Default: 50% of window length
%   nfft     : (optional) FFT length. Default: max(256, 2^nextpow2(window length))
%
% NOTES
%   - Uses Welch PSD estimate (pwelch)
%   - Plots all channels on a single axes (log-log)
%   - Assumes each row is a time series

    narginchk(2,5);

    if isempty(X) || ~ismatrix(X)
        error('X must be a non-empty 2D matrix of size N x Nt.');
    end
    if ~isscalar(Fs) || Fs <= 0
        error('Fs must be a positive scalar (Hz).');
    end

    [N, Nt] = size(X);

    % Defaults
    if nargin < 5 || isempty(window)
        winLen = min(1024, Nt);
        window = hann(winLen, 'periodic');
    else
        if isscalar(window)
            winLen = min(window, Nt);
            window = hann(winLen, 'periodic');
        else
            winLen = min(length(window), Nt);
            window = window(:);
            if length(window) ~= winLen
                window = window(1:winLen);
            end
        end
    end

    if nargin < 6 || isempty(noverlap)
        noverlap = floor(0.5 * winLen);
    else
        noverlap = min(noverlap, winLen-1);
    end

    if nargin < 7 || isempty(nfft)
        nfft = max(256, 2^nextpow2(winLen));
    end

    % Compute PSDs
    for i = 1:N
        xi = X(i,:);
        if all(~isfinite(xi))
            warning('Channel %d contains no finite values; skipping.', i);
            continue;
        end

        % Remove mean (helps with DC dominating)
        %xi = xi - mean(xi, 'omitnan');

        % Replace NaNs/Infs (pwelch can't handle NaNs)
        bad = ~isfinite(xi);
        if any(bad)
            % simple linear interpolation over bad samples
            t = 1:Nt;
            good = ~bad;
            if nnz(good) < 2
                warning('Channel %d has too few valid samples; skipping.', i);
                continue;
            end
            xi(bad) = interp1(t(good), xi(good), t(bad), 'linear', 'extrap');
        end

        [Pxx, f] = pwelch(xi, window, noverlap, nfft, Fs, 'onesided');
    end
end

function [] = plot_residuals(t_dateTime,dY_NSM, noise, sigma_noise)
n  = length(dY_NSM(1, 1, :));
Nt = length(noise);

% define subplot dimensions
[p,~]= numSubplots(n);
rows = p(1); columns = p(2);
figure();
for k = 1:n
    subplot(rows, columns, k); 
    dataPlot = squeeze(dY_NSM(1, :, k))./1E-9 + noise;
    plot(t_dateTime, dataPlot, 'LineStyle','none', 'Marker','*');
    grid on; hold on;
    yline(3*sigma_noise); yline(-3*sigma_noise);

    % stats
    Z = dataPlot./sigma_noise; P_outlier = sum(abs(Z)>3)./ Nt * 100;
    RMS_val = rms(dataPlot);

    % Add text box inside subplot
    txt = sprintf('RMS = %.3e\nP_{out} = %.2f%%', ...
        RMS_val, P_outlier);

    text(0.02, 0.95, txt, ...
        'Units', 'normalized', ...
        'VerticalAlignment', 'top', ...
        'HorizontalAlignment', 'left', ...
        'BackgroundColor', 'w', ...
        'EdgeColor', 'k', ...
        'Margin', 5, ...
        'FontSize', 10);

    xlabel('Time');
    ylabel('Residual [E]');
    title(sprintf('Component %d', k));
end
sgtitle('NSM residuals and 3\sigma bounds')
end

function [p,n]=numSubplots(n)
% function [p,n]=numSubplots(n)
%
% Purpose
% Calculate how many rows and columns of sub-plots are needed to
% neatly display n subplots. 
%
% Inputs
% n - the desired number of subplots.     
%  
% Outputs
% p - a vector length 2 defining the number of rows and number of
%     columns required to show n plots.     
% [ n - the current number of subplots. This output is used only by
%       this function for a recursive call.]
%
%
%
% Example: neatly lay out 13 sub-plots
% >> p=numSubplots(13)
% p = 
%     3   5
% for i=1:13; subplot(p(1),p(2),i), pcolor(rand(10)), end 
%
%
% Rob Campbell - January 2010


while isprime(n) & n>4, 
    n=n+1;
end

p=factor(n);

if length(p)==1
    p=[1,p];
    return
end


while length(p)>2
    if length(p)>=4
        p(1)=p(1)*p(end-1);
        p(2)=p(2)*p(end);
        p(end-1:end)=[];
    else
        p(1)=p(1)*p(2);
        p(2)=[];
    end    
    p=sort(p);
end


%Reformat if the column/row ratio is too large: we want a roughly
%square design 
while p(2)/p(1)>2.5
    N=n+1;
    [p,n]=numSubplots(N); %Recursive!
end
end
