clear; clc;
close all;
addpath('functions/'); 
set(0,'defaultAxesFontSize',16);
%% COMPUTE EIGENVALUES OF ATTITUDE SENSITIVITY FOR MSODP
% Description: using GG observations generated by MSODP, 
% compute the eigenvalues over time for the attitude errors sensitivity.
% Author: Sergio Coll Ibars
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%%                Mesurement mask 
%           xx xy xz yx yy yz zx zy zz
mask     =  [1, 0, 1, 0, 1, 0, 0, 0, 1]';

%%             Read or compute attitude errors
read = 1;

%% Extract GG observations
folderPath = "/Users/sergiocollibars/Documents/GG_observations/120by120";
[GG_obs]   = parser_GG_obs_MSODP(folderPath);

%% plot GG
t0         = datetime(2000,1,1,12,0,0,'TimeZone','UTC');
t_dateTime = t0 + seconds(GG_obs(:, 1));
t          = GG_obs(:, 1); Nt = length(t);

yylbl = ['XX', 'XY', 'XZ', 'YY', 'YZ', 'ZZ'];
figure();
for k = 1:6
    subplot(2, 3, k);
    plot(t_dateTime, GG_obs(:, k+1)./1E-9, 'LineWidth', 2, 'Color', 'b'); 
    title(yylbl(k)); ylabel('[Eotvos]')
    grid on;
end
sgtitle('GG Observations from ' + string(t_dateTime(1)) + ' to ' + ...
    string(t_dateTime(end)));

%% Apply NSM to eliminate 1st order orientation errors
disp('  Computing NSM (eigenvals)')
Nm         = sum(logical(mask));
eigVals    = zeros(Nm, Nt);

for j = 1:Nt 
    g = [GG_obs(j, 2:4),GG_obs(j, 3),GG_obs(j, 5:6),GG_obs(j, 4),...
         GG_obs(j, 6),GG_obs(j, 7)];
    [Hrot_grad] = compute_rotPartials_analy(g', eye(3));
    [S, V, D]   = svd(Hrot_grad(logical(mask), :)');
    vals = sum(V);
    eigVals(:, j) = vals';
end

%% Plot Eigenvalues over time
eps = 1E-20;
figure()
semilogy(t_dateTime, eigVals + eps, 'LineWidth', 2); 
grid on;
title('Eigenvalues over time');
legend(string(1:Nm));

yticks = get(gca, 'YTick');
yticklabels = get(gca, 'YTickLabel');

yticklabels{1} = '0';   % replace smallest tick label
set(gca, 'YTickLabel', yticklabels);

%% COMPUTE STATS
X = eigVals; 

max_val   = max(X, [], 2);
min_val   = min(X, [], 2);
mean_val  = mean(X, 2);
SumS_val   = sqrt(sum(X.^2, 2));
N = length(GG_obs);

T = table((1:Nm)', max_val, min_val, mean_val, ...
    'VariableNames', {'Index','Max','Min','RMS'});
disp("Eigenvalues statistics: ")
disp(T)

sigma_m = 1E-14;    % [s^-2]
sigma_m =  3.15E-15;
T = table((1:Nm)', (3*sigma_m)./max_val, (sigma_m)./(max_val * sqrt(3)), ...
    'VariableNames', {'Index','Max Peak','Mean'});
disp("Atittude error requirements for 3 sigma = " + string(3*sigma_m) + "s^-2")
disp(T)

