clear; clc;
close all;
addpath('functions/'); 
set(0,'defaultAxesFontSize',16);
%% COMPUTE GG OBSERVATION RESIDUALS DUE TO ATTITUDE ERRORS
% Description: using GG observations generated by OMSODP and attitude
% errors according to Encarnacao et.al. 2025, compute the effect of NSM in
% removing atittude errors.
% Author: Sergio Coll Ibars
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%%                Mesurement mask 
%           xx xy xz yx yy yz zx zy zz
mask     =  [1, 1, 1, 0, 1, 1, 0, 0, 1]';

%% Extract GG observations
folderPath = "/Users/sergiocollibars/Desktop/CSML/MSODP_functions/GG_apriori";
[GG_obs]   = parser_GG_obs_MSODP(folderPath);

%% plot GG
t0         = datetime(2000,1,1,12,0,0,'TimeZone','UTC');
t_dateTime = t0 + seconds(GG_obs(:, 1));
t          = GG_obs(:, 1); Nt = length(t);

yylbl = ['XX', 'XY', 'XZ', 'YY', 'YZ', 'ZZ'];
figure();
for k = 1:6
    subplot(2, 3, k);
    plot(t_dateTime, GG_obs(:, k+1)./1E-9, 'LineWidth', 2, 'Color', 'b'); 
    title(yylbl(k)); ylabel('[Eotvos]')
    grid on;
end
sgtitle('GG Observations from ' + string(t_dateTime(1)) + ' to ' + ...
    string(t_dateTime(end)));

%% Compute state errors
disp('  Generating state errors ... ')
fs = 1 / (t(2) -t(1)); % Hz
plotCommand = 0;
[At1] = create_noise_from_PSD(fs, Nt/fs, plotCommand); % yaw error
[At2] = create_noise_from_PSD(fs, Nt/fs, plotCommand); % pitch error
[At3] = create_noise_from_PSD(fs, Nt/fs, plotCommand); % roll error

att_Err = [At1,At2,At3]';

%% Add angular errors
[GG_rot, GG_nom] = rotate_GG_obs(GG_obs,att_Err);
prefit           = GG_rot(:, 2:end) - GG_nom(:, 2:end);

dY               = prefit(:, logical(mask))'; % mask x Nt
signal           = GG_nom(:, 2:end);
signal_mask      = signal(:, logical(mask))';

%% Instrument noise
GG_sigma         = 2^(-1/2) * 1E-14;   % [s^-2 / sqrt(Hz)]
noise            = normrnd(0, GG_sigma * sqrt(fs), [9, Nt]);
noise_mask       = noise(logical(mask), :);

%% Apply NSM to eliminate 1st order orientation errors
idx        = [4 5 6];  
Nm         = sum(logical(mask)) - length(idx);
dY_NSM     = zeros(Nm, Nt); signal_NSM = dY_NSM; noise_NSM = dY_NSM;

for j = 1:Nt 
    [Hrot_grad] = compute_rotPartials_analy(GG_nom(j, 2:end)', eye(3));
    [S, V, D]   = svd(Hrot_grad(logical(mask), :)');
    V_rot       = D(:, idx);
    P_rot       = V_rot * V_rot';

    dY_NSM(:, j)     = V_rot' * dY(:, j);
    signal_NSM(:, j) = V_rot' * signal_mask(:, j);
    noise_NSM(:, j)  = V_rot' * noise_mask(:, j);
end

%% Power Spectral Density of measurement residuals
mask_name = ["xx", "xy", "xz", "yx", "yy", "yz", "zx", "zy", "zz"];
tt  = mask_name(logical(mask));
tt2 = ["x1", "x2", "x3"]; 
pltt = "PSD GG residuals with NSM";
plotPSD_multiChannel(dY_NSM./1E-9, fs, pltt, tt2);

pltt = "PSD GG residuals without NSM";
plotPSD_multiChannel(dY./1E-9, fs, pltt, tt);

%% PSD of the gravity signal
pltt = "PSD GG signal with NSM";
plotPSD_multiChannel(signal_NSM./1E-9, fs, pltt, tt2);

pltt = "PSD GG signal without NSM";
plotPSD_multiChannel(signal_mask./1E-9, fs, pltt, tt);

%% PSD of the GG noise
pltt = "PSD GG noise with NSM";
plotPSD_multiChannel(noise_NSM./1E-9, fs, pltt, tt2);

pltt = "PSD GG noise without NSM";
plotPSD_multiChannel(noise_mask./1E-9, fs, pltt, tt);