function [Hrot] = compute_rotPartials_analy(Y, BN)
    % COMPUTE ROTATION GRAVITY TENSOR PARTIALS
    % Description:  Given the gravity tensor in ACI coordinates, compute
    % the Euler angles partials in the BODY frame.
    % Author: Sergio Coll Ibars
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    
    % rotate to Body frame
    jN = [Y(1), Y(2), Y(3);...
          Y(4), Y(5), Y(6);...
          Y(7), Y(8), Y(9)]; % ACI coordinates
    jB = BN * jN * BN';      % BODY_ACI rotation

    % back to vector notation
    Y = [jB(1,1); jB(1,2) ; jB(1,3); jB(2,1);...
         jB(2,2); jB(2,3) ; jB(3,1); jB(3,2); jB(3,3)];
    
    % solve for rotation matrix
    Yxx = Y(1); Yxy = Y(2); Yxz = Y(3);
    Yyy = Y(5); Yyz = Y(6); Yzz = Y(9);

    h = -[0, 2*Yxz, -2*Yxy;...
           -Yxz, Yyz, Yxx - Yyy;...
        Yxy, Yzz - Yxx, -Yyz;...
        -Yxz, Yyz, Yxx - Yyy;...
        -2*Yyz, 0, 2*Yxy;...
        Yyy - Yzz, -Yxy, Yxz;...
        Yxy, Yzz - Yxx, -Yyz;...
        Yyy - Yzz, -Yxy, Yxz;...
        2*Yyz, -2*Yxz, 0];
    Hrot = [h(:, 3), h(:, 2), h(:, 1)];
end
