#!/bin/bash
#SBATCH -J LS_solv
#SBATCH -p grace   #normal                 # grace-serial      #  normal
#SBATCH -N 1
#SBATCH -n 1
#SBATCH -t 02:00:00
#SBATCH --mem=96G
#SBATCH -o logs/%x_%j.out
#SBATCH -e logs/%x_%j.err

mkdir -p logs

# load modules:
module load python3

# Path with nominal Grav Gradient observations
folder_GG_obs="/Users/sergiocollibars/Documents/GG_observations"

# Path with nominal attitude observations
folder_AttObs_nom="/Users/sergiocollibars/Documents/att_nom"

# Path with true attitude observations
folder_AttObs_true="/Users/sergiocollibars/Documents/att_true"

echo "Starting the atittude residual analysis process..."

python3 -u main.py "$folder_GG_obs" "$folder_AttObs_nom" "$folder_AttObs_true"

echo "Process completed successfully."
